=== Bidura/web_stack_development/payroll2.dtd
<!ELEMENT payroll_management(payroll+)>
<!ELEMENT payroll (empname,salary,email,phno,dept,doj)>
<!ELEMENT empname (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phno (#PCDATA)>
<!ELEMENT dept (#PCDATA)>
<!ELEMENT doj (#PCDATA)>

=== Bidura/web_stack_development/payroll2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="payroll2.xsl"?>
<!DOCTYPE payroll_management SYSTEM "payroll2.dtd">
<payroll_management xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="C://xampp2//htdocs//payroll2.xsd">
<payroll>
<empname>Bidura Sarkar</empname>
<salary>20000</salary>
<email>abc@gmail.com</email>
<phno>1234567890</phno>
<dept>Information Technology</dept>
<doj>13.12.2025</doj>
</payroll>
<payroll>
<empname>Richie astar</empname>
<salary>15000</salary>
<email>abc2@gmail.com</email>
<phno>1234567899</phno>
<dept>Architecture</dept>
<doj>14.12.2021</doj>
</payroll>
<payroll>
<empname>Aniruddha Bandopadhyay</empname>
<salary>20000.56</salary>
<email>abc4@gmail.com</email>
<phno>1234565890</phno>
<dept>Information Technology</dept>
<doj>1.12.2025</doj>
</payroll>
</payroll_management>
